[tools]
fzf = "0.70.0" # renovate: datasource=github-releases depName=junegunn/fzf
ghq = "1.9.4" # renovate: datasource=github-releases depName=x-motemen/ghq
"github-cli" = "2.88.1" # renovate: datasource=github-releases depName=cli/cli
kubectl = "1.35.2" # renovate: datasource=github-tags depName=kubernetes/kubernetes
helm = "4.0.1" # renovate: datasource=github-releases depName=helm/helm
krew = "0.5.0" # renovate: datasource=github-releases depName=kubernetes-sigs/krew
kustomize = "5.8.0" # renovate: datasource=github-releases depName=kubernetes-sigs/kustomize
kind = "0.30.0" # renovate: datasource=github-releases depName=kubernetes-sigs/kind
stern = "1.33.1" # renovate: datasource=github-releases depName=stern/stern
