[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tabline#enabled = 1
    let g:airline_theme = 'murmur'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[pugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'justmao945/vim-clang'
hook_source = '''

let g:clang_auto = 1
let g:clang_complete_auto = 1
let g:clang_auto_select = 0
let g:clang_use_library = 1

let g:clang_exec = 'clang'

let g:clang_exec = 'clang-format'

let g:clang_c_options = '-std=c11'
let g:clang_cpp_options = '-std=c++11 -stdlib=libc++'

'''

[[plugins]]
repo = 'dag/vim2hs'

[[plugins]]
repo = 'hdima/python-syntax'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
