[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source  = '''
    let g:deoplete#enable_at_startup = 1
    inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
on_i = 1
hook_source = '''
    let g:jedi#use_tabs_not_buffers = 1
    let g:jedi#popup_select_first = 0 
    autocmd FileType python setlocal completeopt-=preview
'''


[[plugins]]
repo = 'rhysd/vim-clang-format'
hook_source  = '''
    let g:clang_format#style_options = {
            \ 'AccessModifierOffset' : -4,
            \ 'AllowShortIfStatementsOnASingleLine' : 'true',
            \ 'AlwaysBreakTemplateDeclarations' : 'true',
            \ 'Standard' : 'C++11',
            \ 'BreakBeforeBraces' : 'Stroustrup',
            \ }
'''

