[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <silent><expr> <Tab>
    \ pumvisible() ? "\<C-n>" :
    \ deoplete#mappings#manual_complete()
'''
on_i = 1

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
    let g:jedi#use_tabs_not_buffers = 0
    let g:jedi#popup_select_first = 0 
    autocmd FileType python setlocal completeopt-=preview
'''

