[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp', 'cmake']
on_i = 1
depends = ['deoplete.nvim']
# hook_source = '''
#     let g:deoplete#sources#clang#libclang_path = '/usr/local/Cellar/llvm/4.0.0_1/lib/libclang.dylib'
#     let g:deoplete#sources#clang#clang_header = '/usr/include/'
# '''
hook_source = '''
    let g:deoplete#sources#clang#clang_header = '/usr/include/'
    let g:deoplete#sources#clang#libclang_path = '/usr/lib/libclang.so'
'''


[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
on_i = 1
depends = ['deoplete.nvim']
hook_source = '''
  let g:deoplete#sources#jedi#show_docstring=0
'''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
hook_source = '''
    let g:deoplete#sources#rust#racer_binary='$HOME/.cargo/bin/racer'
'''

[[plugins]]
repo = 'zchee/deoplete-go'
